In [1]:
import pandas as pd
import numpy as np

In [6]:
dataset = 'B'

In [11]:
df = pd.read_csv('data/'+dataset+'.tsv',sep='\t', header=0, index_col=0)
df

In [7]:
df = pd.read_hdf('data/'+dataset+'.h5')
df

,TCGA-OR-A5JP-01A,TCGA-OR-A5JG-01A,TCGA-PK-A5HB-01A,TCGA-OR-A5JE-01A,TCGA-OR-A5KU-01A,TCGA-OR-A5L9-01A,TCGA-OR-A5JQ-01A,TCGA-OR-A5K4-01A,TCGA-OR-A5JL-01A,TCGA-OR-A5LS-01A,...,TCGA-V4-A9ES-01A,TCGA-VD-A8KI-01A,TCGA-VD-A8KL-01A,TCGA-V4-A9F7-01A,TCGA-V4-A9EO-01A,TCGA-WC-A87T-01A,TCGA-WC-AA9A-01A,TCGA-V4-A9EA-01A,TCGA-VD-A8KD-01A,TCGA-V4-A9EX-01A
Composite Element REF,,,,,,,,,,,,,,,,,,,,,
cg00000165,0.883701,0.870551,0.283920,0.831907,0.166760,0.099543,0.100943,0.078832,0.108161,0.133266,...,0.870173,0.229565,0.176223,0.882137,0.096754,0.221580,0.141446,0.169049,0.129985,0.376554
cg00000292,0.853702,0.885412,0.921166,0.679114,0.874738,0.761430,0.877027,0.814372,0.369876,0.840564,...,0.941264,0.767139,0.796392,0.881906,0.823203,0.888148,0.593716,0.769067,0.904206,0.680020
cg00000363,0.508555,0.841909,0.796398,0.179835,0.726879,0.749970,0.714194,0.927625,0.131339,0.841795,...,0.880992,0.094847,0.609082,0.469553,0.269957,0.687909,0.918514,0.887517,0.334024,0.769272
cg00000658,0.848490,0.814400,0.840063,0.858271,0.882336,0.845930,0.814129,0.839736,0.797018,0.869339,...,0.806520,0.829472,0.799493,0.839057,0.820979,0.787881,0.817321,0.837664,0.794118,0.808315
cg00000721,0.944502,0.929823,0.953909,0.950138,0.941715,0.947057,0.933543,0.938294,0.952681,0.944525,...,0.939300,0.946952,0.939708,0.941234,0.935960,0.945435,0.933489,0.945953,0.942678,0.945993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cg13548810,0.270510,0.221659,0.267082,0.281766,0.604042,0.373980,0.531902,0.168363,0.390395,0.296341,...,0.921309,0.903965,0.921298,0.899491,0.942926,0.898295,0.955405,0.907376,0.903849,0.915565
cg13548833,0.900666,0.936315,0.918285,0.914605,0.921135,0.859577,0.887804,0.821659,0.900444,0.927246,...,0.908336,0.903119,0.851160,0.891998,0.905876,0.896349,0.885773,0.875170,0.875415,0.817955
cg13548946,0.879640,0.840469,0.876222,0.882169,0.871450,0.876181,0.866211,0.827444,0.832891,0.876823,...,0.885377,0.864087,0.814403,0.946793,0.888664,0.871731,0.898516,0.890393,0.890140,0.838479
cg13549082,0.723099,0.380080,0.528472,0.717467,0.268518,0.300414,0.417596,0.448190,0.627939,0.373930,...,0.697029,0.547540,0.521546,0.762704,0.702750,0.721839,0.709213,0.596137,0.541311,0.466133
cg13549174,0.853292,0.863391,0.798671,0.869302,0.894982,0.883315,0.788554,0.284406,0.895814,0.916066,...,0.904898,0.899109,0.917329,0.926410,0.917033,0.892185,0.896248,0.906826,0.817935,0.890322

In [8]:
np.save("data/B/Without nan/"+dataset+"_samples.npy",df.columns.to_numpy())

In [9]:
np.save("data/B/Without nan/"+dataset+"_features.npy",df.index.to_numpy())

In [10]:
df2 = df.reset_index(drop=True)
df2

,TCGA-OR-A5JP-01A,TCGA-OR-A5JG-01A,TCGA-PK-A5HB-01A,TCGA-OR-A5JE-01A,TCGA-OR-A5KU-01A,TCGA-OR-A5L9-01A,TCGA-OR-A5JQ-01A,TCGA-OR-A5K4-01A,TCGA-OR-A5JL-01A,TCGA-OR-A5LS-01A,...,TCGA-V4-A9ES-01A,TCGA-VD-A8KI-01A,TCGA-VD-A8KL-01A,TCGA-V4-A9F7-01A,TCGA-V4-A9EO-01A,TCGA-WC-A87T-01A,TCGA-WC-AA9A-01A,TCGA-V4-A9EA-01A,TCGA-VD-A8KD-01A,TCGA-V4-A9EX-01A
0,0.883701,0.870551,0.283920,0.831907,0.166760,0.099543,0.100943,0.078832,0.108161,0.133266,...,0.870173,0.229565,0.176223,0.882137,0.096754,0.221580,0.141446,0.169049,0.129985,0.376554
1,0.853702,0.885412,0.921166,0.679114,0.874738,0.761430,0.877027,0.814372,0.369876,0.840564,...,0.941264,0.767139,0.796392,0.881906,0.823203,0.888148,0.593716,0.769067,0.904206,0.680020
2,0.508555,0.841909,0.796398,0.179835,0.726879,0.749970,0.714194,0.927625,0.131339,0.841795,...,0.880992,0.094847,0.609082,0.469553,0.269957,0.687909,0.918514,0.887517,0.334024,0.769272
3,0.848490,0.814400,0.840063,0.858271,0.882336,0.845930,0.814129,0.839736,0.797018,0.869339,...,0.806520,0.829472,0.799493,0.839057,0.820979,0.787881,0.817321,0.837664,0.794118,0.808315
4,0.944502,0.929823,0.953909,0.950138,0.941715,0.947057,0.933543,0.938294,0.952681,0.944525,...,0.939300,0.946952,0.939708,0.941234,0.935960,0.945435,0.933489,0.945953,0.942678,0.945993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140058,0.270510,0.221659,0.267082,0.281766,0.604042,0.373980,0.531902,0.168363,0.390395,0.296341,...,0.921309,0.903965,0.921298,0.899491,0.942926,0.898295,0.955405,0.907376,0.903849,0.915565
140059,0.900666,0.936315,0.918285,0.914605,0.921135,0.859577,0.887804,0.821659,0.900444,0.927246,...,0.908336,0.903119,0.851160,0.891998,0.905876,0.896349,0.885773,0.875170,0.875415,0.817955
140060,0.879640,0.840469,0.876222,0.882169,0.871450,0.876181,0.866211,0.827444,0.832891,0.876823,...,0.885377,0.864087,0.814403,0.946793,0.888664,0.871731,0.898516,0.890393,0.890140,0.838479
140061,0.723099,0.380080,0.528472,0.717467,0.268518,0.300414,0.417596,0.448190,0.627939,0.373930,...,0.697029,0.547540,0.521546,0.762704,0.702750,0.721839,0.709213,0.596137,0.541311,0.466133
140062,0.853292,0.863391,0.798671,0.869302,0.894982,0.883315,0.788554,0.284406,0.895814,0.916066,...,0.904898,0.899109,0.917329,0.926410,0.917033,0.892185,0.896248,0.906826,0.817935,0.890322

In [11]:
arr = df2.to_numpy()
arr

array([[0.8837011 , 0.87055148, 0.28391988, ..., 0.16904908, 0.12998478,
        0.37655391],
       [0.85370214, 0.88541156, 0.92116616, ..., 0.76906717, 0.90420629,
        0.68002046],
       [0.50855528, 0.84190918, 0.79639825, ..., 0.88751706, 0.33402438,
        0.76927164],
       ...,
       [0.87963988, 0.84046912, 0.87622184, ..., 0.89039296, 0.89013973,
        0.83847853],
       [0.72309859, 0.38008002, 0.52847176, ..., 0.59613665, 0.54131115,
        0.46613333],
       [0.85329173, 0.86339132, 0.79867075, ..., 0.90682565, 0.81793546,
        0.89032232]])

In [12]:
np.save('data/B/Without nan/'+dataset+'.npy', arr)

# Load from npy

In [87]:
import pandas as pd
import numpy as np
from sklearnex import patch_sklearn
patch_sklearn()
from sklearn.impute import SimpleImputer

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)

In [2]:
dataset = 'B'

In [3]:
values = np.load('data/'+dataset+'.npy', allow_pickle=True)
features = np.load('data/'+dataset+ '_features.npy', allow_pickle=True)
samples = np.load('data/'+dataset+ '_samples.npy', allow_pickle=True)

In [2]:
dataset = 'B'
values = np.load('data/B_withna/'+dataset+'.npy', allow_pickle=True)
features = np.load('data/B_withna/'+dataset+ '_features.npy', allow_pickle=True)
samples = np.load('data/B_withna/'+dataset+ '_samples.npy', allow_pickle=True)

In [88]:
dataset = 'A'
Avalues = np.load('data/'+dataset+'.npy', allow_pickle=True)
Afeatures = np.load('data/'+dataset+ '_features.npy', allow_pickle=True)
Asamples = np.load('data/'+dataset+ '_samples.npy', allow_pickle=True)

In [89]:
dataset = 'C'
Cvalues = np.load('data/'+dataset+'.npy', allow_pickle=True)
Cfeatures = np.load('data/'+dataset+ '_features.npy', allow_pickle=True)
Csamples = np.load('data/'+dataset+ '_samples.npy', allow_pickle=True)

In [ ]:
# # df = pd.DataFrame(daata=values, index=features, columns=samples)
# df

In [4]:
values.shape
samples.shape

(9736,)

In [5]:
Asamples.shape

(11057,)

In [6]:
A_B = np.setdiff1d(Asamples, samples)

In [7]:
A_B.shape

(1976,)

In [8]:
Bs = np.append(samples, A_B)
Bs.shape

(11712,)

In [9]:
B_A = np.setdiff1d(samples, Asamples)

In [10]:
B_A.shape

(655,)

In [11]:
new_col = np.empty((features.shape[0], A_B.shape[0]))
new_col.fill(np.nan)
new_col.shape

(485577, 1976)

In [12]:
values.shape

(485577, 9736)

In [13]:
Bv = np.hstack([values, new_col])
Bv.shape

(485577, 11712)

In [16]:
As = np.append(Asamples, B_A)
As.shape

(11712,)

In [17]:
values.shape

(485577, 9736)

In [18]:
new_col = np.empty((Afeatures.shape[0], B_A.shape[0]))
new_col.fill(np.nan)
new_col.shape

(60483, 655)

In [72]:
Avalues.shape

(60483, 11057)

In [20]:
Av = np.hstack([Avalues, new_col])
Av.shape

(60483, 11712)

In [50]:
np.save('data/AB_meanimp/A_samples.npy', As)
np.save('data/AB_meanimp/B_samples.npy', Bs)

# Mean imputation

In [21]:
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean', verbose=2)

In [22]:
A = Av.T

In [23]:
A.shape

(11712, 60483)

In [24]:
A_new = imp_mean.fit_transform(A)

In [25]:
A_new.shape

(11712, 60483)

In [26]:
np.save('data/AB_meanimp/'+dataset+'.npy', A_new.T)

In [14]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean', verbose=2)

In [15]:
B = Bv.T

In [16]:
B.shape

(11712, 485577)

In [17]:
B_new = imp_mean.fit_transform(B)
B_new.shape

In [ ]:
mask = np.isnan(B)

Error: Session cannot generate requests

In [ ]:
mask[:,0].all()

Error: Session cannot generate requests

In [ ]:
features_list = []
for i in range(mask.shape[1]):
    if i % 100000 == 0:
        print(i)
    if not mask[:,i].all():
        features_list.append(i)

0
100000
200000
300000
400000

In [ ]:
fl = features[features_list]

In [ ]:
fl.shape

(396065,)

In [ ]:
dataset = 'B'

In [ ]:
np.save('data/AB_meanimp/'+dataset+'.npy', B_new.T)

In [ ]:
np.save('data/AB_meanimp/'+dataset+'_features.npy', fl)

# Zero imputation

In [7]:
imp_zero = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value=0.0, verbose=1)

In [8]:
X = values.T

In [10]:
X_new = imp_zero.fit_transform(X)

In [12]:
X_new.shape

(9736, 485577)

In [13]:
np.save('data/B_zeroimp/'+dataset+'.npy', X_new.T)

# C

In [4]:
dataset = 'C'
Cvalues = np.load('data/'+dataset+'.npy', allow_pickle=True)
Cfeatures = np.load('data/'+dataset+ '_features.npy', allow_pickle=True)
Csamples = np.load('data/'+dataset+ '_samples.npy', allow_pickle=True)

In [12]:
np.setdiff1d(Csamples, samples).shape

(1923,)

In [15]:
np.isnan(Cvalues).any()

False

In [16]:
from functools import reduce
ABC = reduce(np.union1d, (Asamples, samples, Csamples))

In [31]:
ABC.shape

(11916,)

In [40]:
Aextra = np.setdiff1d(ABC, Asamples)
Aextra.shape

(859,)

In [37]:
new_col = np.empty((Afeatures.shape[0], Aextra.shape[0]))
new_col.fill(np.nan)
new_col.shape

(60483, 859)

In [38]:
Avalues.shape

(60483, 11057)

In [39]:
Av = np.hstack([Avalues, new_col])
Av.shape

(60483, 11916)

In [41]:
Bextra = np.setdiff1d(ABC, samples)
print(Bextra.shape)
new_col = np.empty((features.shape[0], Bextra.shape[0]))
new_col.fill(np.nan)
print(new_col.shape)
print(values.shape)
Bv = np.hstack([values, new_col])
Bv.shape

(2180,)
(485577, 2180)
(485577, 9736)

(485577, 11916)

In [42]:
Cextra = np.setdiff1d(ABC, Csamples)
print(Cextra.shape)
new_col = np.empty((Cfeatures.shape[0], Cextra.shape[0]))
new_col.fill(np.nan)
print(new_col.shape)
print(values.shape)
Cv = np.hstack([Cvalues, new_col])
Cv.shape

(896,)
(1881, 896)
(485577, 9736)

(1881, 11916)

# Intersection

In [7]:
from functools import reduce
ABC = reduce(np.intersect1d, (Asamples, samples, Csamples))

In [35]:
ABC.shape

(8895,)

In [10]:
Asamples.shape

(11057,)

In [11]:
dataset='A'

In [21]:
# np.save('data/ABC_inter/A_samples.npy', ABC)
# np.savetxt('data/ABC_inter/sample_list.tsv', ABC, delimiter='\t')
sampdf = pd.DataFrame(ABC)
sampdf

                     0
0     TCGA-05-4384-01A
1     TCGA-05-4390-01A
2     TCGA-05-4396-01A
3     TCGA-05-4405-01A
4     TCGA-05-4410-01A
...                ...
8890  TCGA-ZS-A9CG-01A
8891  TCGA-ZT-A8OM-01A
8892  TCGA-ZU-A8S4-01A
8893  TCGA-ZU-A8S4-11A
8894  TCGA-ZX-AA5X-01A

[8895 rows x 1 columns]

In [22]:
sampdf = sampdf.set_index(0)

In [27]:
sampdf.to_csv('data/ABC_inter/sample_list.tsv', sep='\t', header=False)

In [33]:
sample = np.loadtxt('data/ABC_inter/sample_list.tsv', delimiter='\t', dtype='<U32')

In [34]:
sample.shape

(8895,)

# Mean imputation

In [43]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean', verbose=2)

In [44]:
A = Av.T

In [45]:
A.shape

(11916, 60483)

In [46]:
A_new = imp_mean.fit_transform(A)

In [47]:
A_new.shape

(11916, 60483)

In [48]:
np.save('data/ABC_meanimp/'+dataset+'.npy', A_new.T)

In [49]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean', verbose=2)

In [50]:
B = Bv.T

In [51]:
B.shape

(11916, 485577)

In [ ]:
B_new = imp_mean.fit_transform(B)
B_new.shape

In [ ]:
mask = np.isnan(B)

Error: Session cannot generate requests

In [ ]:
mask[:,0].all()

False

In [ ]:
features_list = []
for i in range(mask.shape[1]):
    if i % 100000 == 0:
        print(i)
    if not mask[:,i].all():
        features_list.append(i)

0
100000
200000
300000
400000

In [ ]:
fl = features[features_list]

In [ ]:
fl.shape

(396065,)

In [ ]:
dataset = 'B'

In [ ]:
np.save('data/ABC_meanimp/'+dataset+'.npy', B_new.T)

In [ ]:
np.save('data/ABC_meanimp/'+dataset+'_features.npy', fl)

# Labels

In [45]:
labels_df = pd.read_csv('./data/labels.tsv', sep='\t', header=0, index_col=0)

In [46]:
labels_df.value_counts()

sample_type.samples
8                      2684
1                      1121
10                      631
3                       623
0                       603
2                       554
6                       543
20                      538
5                       530
14                      515
4                       511
9                       505
24                      478
18                      474
21                      443
12                      417
17                      380
26                      357
7                       309
15                      293
13                      266
11                      186
28                      186
22                      184
30                      173
23                      156
25                      126
27                      113
19                       92
31                       87
16                       80
29                       57
32                       52
33                       51
dtype: int64

In [47]:
samples.shape

(9736,)

In [48]:
Asamples.shape

(11057,)

In [49]:
AB = np.intersect1d(Asamples, samples, return_indices=True)

In [53]:
AB[0].shape

(9081,)

In [54]:
gbm = labels_df[labels_df['sample_type.samples']==10]

In [57]:
gbm

                  sample_type.samples
sample
TCGA-32-1986-01A                   10
TCGA-06-2566-01A                   10
TCGA-02-0047-01A                   10
TCGA-14-1458-01A                   10
TCGA-06-0159-01A                   10
...                               ...
TCGA-08-0522-01A                   10
TCGA-06-2565-01A                   10
TCGA-08-0521-01A                   10
TCGA-06-A5U0-01A                   10
TCGA-06-0128-01A                   10

[631 rows x 1 columns]

In [59]:
gbm_ab = np.intersect1d(gbm.index, AB[0], return_indices=True)

In [62]:
gbm_ab[0]

array(['TCGA-06-0125-01A', 'TCGA-06-0125-02A', 'TCGA-06-0152-02A',
       'TCGA-06-0171-02A', 'TCGA-06-0190-01A', 'TCGA-06-0190-02A',
       'TCGA-06-0210-01A', 'TCGA-06-0210-02A', 'TCGA-06-0211-01A',
       'TCGA-06-0211-02A', 'TCGA-06-0221-02A', 'TCGA-06-1804-01A',
       'TCGA-06-5408-01A', 'TCGA-06-5410-01A', 'TCGA-06-5411-01A',
       'TCGA-06-5412-01A', 'TCGA-06-5413-01A', 'TCGA-06-5414-01A',
       'TCGA-06-5416-01A', 'TCGA-06-5417-01A', 'TCGA-06-5418-01A',
       'TCGA-06-5856-01A', 'TCGA-06-5858-01A', 'TCGA-06-5859-01A',
       'TCGA-12-5295-01A', 'TCGA-12-5299-01A', 'TCGA-14-0736-02A',
       'TCGA-14-0781-01B', 'TCGA-14-1034-02B', 'TCGA-14-1402-02A',
       'TCGA-15-1444-01A', 'TCGA-19-0957-02A', 'TCGA-19-1389-02A',
       'TCGA-19-4065-01A', 'TCGA-19-4065-02A', 'TCGA-19-5960-01A',
       'TCGA-26-1442-01A', 'TCGA-26-5132-01A', 'TCGA-26-5133-01A',
       'TCGA-26-5134-01A', 'TCGA-26-5135-01A', 'TCGA-26-5136-01B',
       'TCGA-26-5139-01A', 'TCGA-28-2510-01A', 'TCGA-28-5204-01A',
       'TCGA-28-5207-01A', 'TCGA-28-5208-01A', 'TCGA-28-5209-01A',
       'TCGA-28-5213-01A', 'TCGA-28-5215-01A', 'TCGA-28-5216-01A',
       'TCGA-28-5218-01A', 'TCGA-28-5220-01A', 'TCGA-32-1980-01A',
       'TCGA-32-5222-01A', 'TCGA-41-5651-01A', 'TCGA-76-4925-01A',
       'TCGA-76-4926-01B', 'TCGA-76-4927-01A', 'TCGA-76-4928-01B',
       'TCGA-76-4929-01A', 'TCGA-76-4931-01A', 'TCGA-76-4932-01A'],
      dtype=object)

In [63]:
Cs = np.append(Csamples, gbm_ab[0])
Cs.shape

(11083,)

In [64]:
Csamples.shape

(11020,)

In [67]:
ABC_new = np.append(ABC.reshape(-1,1), gbm_ab[0])
ABC_new.shape

(8958,)

In [69]:
sampdf = pd.DataFrame(ABC_new)
sampdf = sampdf.set_index(0)
sampdf.to_csv('data/ABC_inter/sample_list.tsv', sep='\t', header=False)
sample = np.loadtxt('data/ABC_inter/sample_list.tsv', delimiter='\t', dtype='<U32')

In [71]:
sample.shape

(8958,)

In [73]:
new_col = np.empty((Cfeatures.shape[0], gbm_ab[0].shape[0]))
new_col.fill(np.nan)
new_col.shape

(1881, 63)

In [74]:
Cvalues.shape

(1881, 11020)

In [76]:
Cv = np.hstack([Cvalues, new_col])
Cv.shape

(1881, 11083)

In [ ]:
np.save('data/AB_meanimp/A_samples.npy', As)
np.save('data/AB_meanimp/B_samples.npy', Bs)

In [78]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean', verbose=2)

In [79]:
C = Cv.T

In [80]:
C.shape

(11083, 1881)

In [81]:
C_new = imp_mean.fit_transform(C)

In [82]:
C_new.shape

(11083, 1881)

In [83]:
dataset = 'C'

In [84]:
np.save('data/'+dataset+'.npy', C_new.T)

In [85]:
Cs.shape

(11083,)

In [86]:
np.save('data/'+dataset+'_samples.npy', Cs)

# Normalization

In [1]:
import pandas as pd
import numpy as np
from sklearnex import patch_sklearn
patch_sklearn()
from sklearn.preprocessing import Normalizer
transformer = Normalizer()
A_new = transformer.fit_transform(A)

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)

In [104]:
Avalues = np.load('data/AB_inter/A.npy', allow_pickle=True)

In [2]:
Bvalues = np.load('data/ABC_inter/B.npy', allow_pickle=True)

In [ ]:
dataset = 'C'
Cvalues = np.load('data/'+dataset+'.npy', allow_pickle=True)
Cfeatures = np.load('data/'+dataset+ '_features.npy', allow_pickle=True)
Csamples = np.load('data/'+dataset+ '_samples.npy', allow_pickle=True)

In [105]:
A = Avalues.T
A.shape

(9081, 60483)

In [3]:
B = Bvalues.T
B.shape

(9736, 396065)

In [92]:
C = Cvalues.T
C.shape

(11083, 1881)

In [106]:
transformer = Normalizer()
A_new = transformer.fit_transform(A)

In [4]:
transformer = Normalizer()
B_new = transformer.fit_transform(B)

In [94]:
transformer = Normalizer()
C_new = transformer.fit_transform(C)

In [102]:
np.save('data/AB_inter/A.npy', A_new.T)

In [ ]:
np.save('data/ABC_inter/Normalized/B.npy', B_new.T)

In [103]:
np.save('data/ABC_inter/C.npy', C_new.T)

In [11]:
dataset = 'C'
Cfeatures = np.load('data/ABC_inter/'+dataset+'_features.npy', allow_pickle=True)

In [18]:
np.unique(Cfeatures).shape

(1881,)

In [1]:
import pandas as pd

In [2]:
df_samples = pd.read_csv('data/ABC_inter/sample_list.tsv', sep='\t', index_col=0)

In [5]:
df_samples.shape[0] * 0.8

7165.6

# Survival data labels preprocessing

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('data/GDC-PANCAN.survival.tsv', sep='\t')

In [4]:
df

                     sample  OS          _PATIENT  OS.time
0          TCGA-OR-A5KZ-01A   1      TCGA-OR-A5KZ      125
1          TCGA-OR-A5LC-01A   1      TCGA-OR-A5LC      159
2          TCGA-P6-A5OF-01A   1      TCGA-P6-A5OF      207
3          TCGA-OR-A5JU-01A   1      TCGA-OR-A5JU      289
4          TCGA-OR-A5K9-11A   1      TCGA-OR-A5K9      344
...                     ...  ..               ...      ...
18487  TARGET-50-PADYUS-01A   0  TARGET-50-PADYUS     4778
18488  TARGET-50-PADXAY-01A   0  TARGET-50-PADXAY     4795
18489  TARGET-50-PADYAS-01A   0  TARGET-50-PADYAS     4811
18490  TARGET-50-PADWKZ-01A   0  TARGET-50-PADWKZ     4819
18491  TARGET-50-PAJLJG-01A   0  TARGET-50-PAJLJG     4937

[18492 rows x 4 columns]

In [10]:
df = df[~df['sample'].isnull()]

In [11]:
df.shape

(18492, 4)

In [12]:
df = df[~df['sample'].astype(str).str.startswith('TARGET')]

In [13]:
df.shape

(13833, 4)

In [14]:
df = df.set_index('sample')

In [15]:
df.shape

(13833, 3)

In [17]:
df = df.drop(columns={'_PATIENT'})

In [19]:
df = df[['OS.time', 'OS']]

In [23]:
df.to_csv("survival.tsv", sep="\t")

In [26]:
df = pd.read_csv('data/survival.tsv', sep='\t', header=0, index_col=0)

In [27]:
df

                  OS.time  OS
sample
TCGA-OR-A5KZ-01A      125   1
TCGA-OR-A5LC-01A      159   1
TCGA-P6-A5OF-01A      207   1
TCGA-OR-A5JU-01A      289   1
TCGA-OR-A5K9-11A      344   1
...                   ...  ..
TCGA-WC-A87U-01A     1581   1
TCGA-WC-A87W-01A     1703   0
TCGA-YZ-A980-01A     1862   0
TCGA-V4-A9E5-01A     2499   0
TCGA-WC-A87T-01A     2600   0

[13833 rows x 2 columns]

In [1]:
import pandas as pd

In [103]:
# read sample_list.tsv in ABC_inter directory
df = pd.read_csv('data/ABC_inter/sample_lists/classification/sample_list.tsv', sep='\t', header=0)

In [104]:
# check df shape
df.shape

(8957, 1)

In [105]:
# df head
df.head()

   TCGA-05-4384-01A
0  TCGA-05-4390-01A
1  TCGA-05-4396-01A
2  TCGA-05-4405-01A
3  TCGA-05-4410-01A
4  TCGA-05-4415-01A

In [106]:
surv_list = ['TCGA-05-4410-01A', 'TCGA-06-AABW-11A', 'TCGA-2G-AAKO-01A', 'TCGA-2G-AAKO-05A', 'TCGA-2G-AALF-01A', 'TCGA-2G-AALG-01A', 'TCGA-2G-AALN-01A', 'TCGA-2G-AALO-01A', 'TCGA-2G-AALQ-01A', 'TCGA-2G-AALR-01A', 'TCGA-2G-AALS-01A', 'TCGA-2G-AALT-01A', 'TCGA-2G-AALW-01A', 'TCGA-2G-AALX-01A', 'TCGA-2G-AALY-01A', 'TCGA-2G-AALZ-01A', 'TCGA-2G-AAM2-01A', 'TCGA-2G-AAM3-01A', 'TCGA-2G-AAM4-01A', 'TCGA-2V-A95S-01A', 'TCGA-3M-AB47-01A', 'TCGA-56-6546-01A', 'TCGA-5M-AAT5-01A', 'TCGA-5M-AATA-01A', 'TCGA-63-5128-01A', 'TCGA-63-5131-01A', 'TCGA-63-A5M9-01A', 'TCGA-63-A5MU-01A', 'TCGA-6A-AB49-01A', 'TCGA-75-5122-01A', 'TCGA-75-5126-01A', 'TCGA-75-6203-01A', 'TCGA-75-6205-01A', 'TCGA-75-6207-01A', 'TCGA-75-6211-01A', 'TCGA-75-7030-01A', 'TCGA-75-7031-01A', 'TCGA-77-A5GB-01B', 'TCGA-79-5596-01A', 'TCGA-80-5607-01A', 'TCGA-86-8281-01A', 'TCGA-A2-A25D-01A', 'TCGA-A3-A8OU-01A', 'TCGA-A3-A8OX-01A', 'TCGA-A4-A772-01A', 'TCGA-A4-A7UZ-01A', 'TCGA-AA-3712-01A', 'TCGA-AB-2890-03A', 'TCGA-AB-2891-03A', 'TCGA-AB-2910-03A', 'TCGA-AB-2915-03A', 'TCGA-AB-2918-03A', 'TCGA-AB-2921-03A', 'TCGA-AB-2930-03A', 'TCGA-AB-2931-03A', 'TCGA-AB-2932-03A', 'TCGA-AB-2940-03A', 'TCGA-AB-2941-03A', 'TCGA-AB-2943-03A', 'TCGA-AB-2944-03A', 'TCGA-AB-2946-03A', 'TCGA-AB-2975-03A', 'TCGA-AC-A23H-01A', 'TCGA-AC-A23H-11A', 'TCGA-AC-A3W6-01A', 'TCGA-AD-A5EJ-01A', 'TCGA-AG-3725-01A', 'TCGA-AG-A01W-01A', 'TCGA-AG-A01Y-01A', 'TCGA-AJ-A3BH-01A', 'TCGA-AX-A3FV-01A', 'TCGA-B0-5104-01A', 'TCGA-BR-6454-01A', 'TCGA-BR-8486-01A', 'TCGA-BR-8679-01A', 'TCGA-BR-A4CR-01A', 'TCGA-BW-A5NP-01A', 'TCGA-BW-A5NQ-01A', 'TCGA-C8-A26Y-01A', 'TCGA-CC-A9FU-01A', 'TCGA-CC-A9FV-01A', 'TCGA-CD-5804-01A', 'TCGA-CF-A9FH-01A', 'TCGA-CG-5716-01A', 'TCGA-CJ-5689-01A', 'TCGA-CK-5915-01A', 'TCGA-CK-6746-01A', 'TCGA-CL-5918-01A', 'TCGA-CQ-A4CA-01A', 'TCGA-CS-5390-01A', 'TCGA-D1-A0ZQ-01A', 'TCGA-D3-A3C1-06A', 'TCGA-D3-A3C3-06A', 'TCGA-D3-A51G-06A', 'TCGA-D3-A8GO-06A', 'TCGA-D8-A1JK-01A', 'TCGA-E2-A9RU-01A', 'TCGA-EB-A41A-01A', 'TCGA-EB-A430-01A', 'TCGA-EK-A3GM-01A', 'TCGA-ER-A19O-06A', 'TCGA-F1-6177-01A', 'TCGA-F5-6810-01A', 'TCGA-FL-A1YF-11A', 'TCGA-FL-A1YG-11A', 'TCGA-FL-A1YH-11A', 'TCGA-FL-A1YI-11A', 'TCGA-FL-A1YL-11A', 'TCGA-FL-A1YM-11A', 'TCGA-FL-A1YN-11A', 'TCGA-FL-A1YQ-11A', 'TCGA-FL-A1YT-11A', 'TCGA-FL-A1YU-11A', 'TCGA-FL-A3WE-11A', 'TCGA-FR-A3YO-06A', 'TCGA-FY-A3NN-01A', 'TCGA-G4-6298-01A', 'TCGA-G4-6302-01A', 'TCGA-GC-A6I1-01A', 'TCGA-GC-A6I3-01A', 'TCGA-GC-A6I3-11A', 'TCGA-GV-A3QG-01A', 'TCGA-HE-7128-01A', 'TCGA-HF-7131-01A', 'TCGA-HR-A5NC-01A', 'TCGA-HZ-A8P0-01A', 'TCGA-IN-A6RO-01A', 'TCGA-KN-8430-01A', 'TCGA-L5-A43J-01A', 'TCGA-LL-A6FP-01A', 'TCGA-LP-A4AV-01A', 'TCGA-MB-A5Y9-01A', 'TCGA-ND-A4WA-01A', 'TCGA-NH-A5IV-01A', 'TCGA-NQ-A638-01A', 'TCGA-P5-A5ET-01A', 'TCGA-P5-A5EU-01A', 'TCGA-PL-A8LV-01A', 'TCGA-QN-A5NN-01A', 'TCGA-R8-A6YH-01A', 'TCGA-RC-A6M3-01A', 'TCGA-RP-A695-06A', 'TCGA-RP-A6K9-06A', 'TCGA-TQ-A7RS-01A', 'TCGA-TS-A8AV-01A', 'TCGA-UE-A6QU-01A', 'TCGA-UY-A8OC-01A', 'TCGA-VB-A8QN-01A', 'TCGA-VQ-A923-01A', 'TCGA-X6-A7WA-01A', 'TCGA-X7-A8D9-01A', 'TCGA-XV-A9VZ-01A', 'TCGA-YD-A9TB-06A', 'TCGA-ZJ-A8QO-01A', 'TCGA-ZJ-AAX8-01A', 'TCGA-ZJ-AAXB-01A', 'TCGA-ZJ-AAXD-01A', 'TCGA-ZJ-AAXF-01A', 'TCGA-ZJ-AAXI-01A', 'TCGA-ZJ-AAXJ-01A', 'TCGA-ZJ-AAXN-01A', 'TCGA-ZJ-AAXT-01A', 'TCGA-ZJ-AB0H-01A', 'TCGA-ZJ-AB0I-01A', 'TCGA-28-2510-01A']

In [108]:
# remove values present in the list from first column of df
df = df.drop(df[df['TCGA-05-4384-01A'].isin(surv_list)].index)

In [109]:
df.shape

(8792, 1)

In [110]:
df.head()

   TCGA-05-4384-01A
0  TCGA-05-4390-01A
1  TCGA-05-4396-01A
2  TCGA-05-4405-01A
4  TCGA-05-4415-01A
5  TCGA-05-4417-01A

In [112]:
df = df.set_index('TCGA-05-4384-01A')

In [113]:
df.to_csv('data/ABC_inter/sample_lists/all/sample_list.tsv', sep='\t')

In [114]:
df.to_csv('data/ABC_inter/sample_list.tsv', sep='\t')

# Preprocessing age

In [120]:
import pandas as pd
import numpy as np
from sklearnex import patch_sklearn
patch_sklearn()
from sklearn.preprocessing import Normalizer
from sklearn.impute import SimpleImputer

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)

In [116]:
df = pd.read_csv('data/ABC_inter/values.tsv', sep='\t', header=0, index_col=0)

In [117]:
df

                  Age at Diagnosis in Years
sample
TCGA-69-7978-01A                       59.0
TCGA-AR-A24Z-01A                       57.0
TCGA-D1-A103-01A                       87.0
TCGA-24-1435-01A                       57.0
TCGA-63-A5MB-01A                       62.0
...                                     ...
TCGA-3G-AB0T-11A                       45.0
TCGA-44-6775-11A                       72.0
TCGA-BJ-A0Z0-01A                       55.0
TCGA-A5-A0G2-01A                       57.0
TCGA-22-A5C4-01A                       70.0

[14318 rows x 1 columns]

In [124]:
df.iloc[:,0].isnull().sum()

0

In [122]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean', verbose=2)
df.iloc[:,0] = imp_mean.fit_transform(df.iloc[:,0].values.reshape(-1,1))

In [125]:
df

                  Age at Diagnosis in Years
sample
TCGA-69-7978-01A                       59.0
TCGA-AR-A24Z-01A                       57.0
TCGA-D1-A103-01A                       87.0
TCGA-24-1435-01A                       57.0
TCGA-63-A5MB-01A                       62.0
...                                     ...
TCGA-3G-AB0T-11A                       45.0
TCGA-44-6775-11A                       72.0
TCGA-BJ-A0Z0-01A                       55.0
TCGA-A5-A0G2-01A                       57.0
TCGA-22-A5C4-01A                       70.0

[14318 rows x 1 columns]

In [126]:
df.to_csv('data/ABC_inter/values.tsv', sep='\t')

In [127]:
transformer = Normalizer()
df.iloc[:,0] = transformer.fit_transform(df.iloc[:,0].values.reshape(-1,1))

In [128]:
df.to_csv('data/ABC_inter/Normalized/values.tsv', sep='\t')

# Preprocessing survival data

In [129]:
df = pd.read_csv('data/ABC_inter/survival.tsv', sep='\t', header=0, index_col=0)

In [130]:
df

                  OS.time  OS
sample
TCGA-OR-A5KZ-01A      125   1
TCGA-OR-A5LC-01A      159   1
TCGA-P6-A5OF-01A      207   1
TCGA-OR-A5JU-01A      289   1
TCGA-OR-A5K9-11A      344   1
...                   ...  ..
TCGA-WC-A87U-01A     1581   1
TCGA-WC-A87W-01A     1703   0
TCGA-YZ-A980-01A     1862   0
TCGA-V4-A9E5-01A     2499   0
TCGA-WC-A87T-01A     2600   0

[13833 rows x 2 columns]

In [131]:
df['OS.time'].isnull().sum()

0

In [ ]:
#def